services:
  db:
    image: supabase/postgres:15.6.1.117
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cozycoder_dev
    ports:
      - "127.0.0.1:5432:5432"
