import Config

# Use Supabase TLS certificate for database connections.
config :cozycoder, CozyCoder.Repo, ssl: [cacertfile: "/app/prod-ca-2021.crt"]

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :cozycoder, CozyCoderWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Disable user registration
config :cozycoder, user_registration: false

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: CozyCoder.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
